export const HotdealInfoCardStyles = {
  infoContainerStyle: 'flex w-full flex-col gap-2',
  infoCardContainerStyle: 'flex flex-col gap-1',
  infoNameStyle: 'font-[var(--font-bold)]',
  infoPriceNTimeWrapper: 'flex justify-between',
  startPriceStyle: 'text-xs text-[var(--text-disabled)] line-through',
  currentPriceWrapperStyle: 'flex gap-2',
  discountPercentStyle: 'text-[var(--text-error)]',
  currentPriceStyle: 'font-[var(--font-bold)]',
  countdownContainerStyle: 'text-right',
  countdownStyle: 'text-[var(--text-error)]',
  quantityContainerStyle: 'flex justify-between',
  currentQuantityWrapperStyle: 'font-[var(--font-bold)]',
  currentQuantityStyle: 'font-[var(--font-bold)]',
  gradeStyle: 'text-sm',
  descriptionContainerStyle: 'mt-8 flex flex-col gap-2',
  descriptionTitleStyle: 'text-lg font-[var(--font-semibold)]',
  descriptionTextStyle: 'whitespace-pre-line',
};
